/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package test;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Abdul Ahad
 */
public class Db extends javax.swing.JFrame {

    /**
     * Creates new form Lab8
     */
    public Db() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Option1Panel = new javax.swing.JPanel();
        Option1 = new javax.swing.JLabel();
        Option2Panel = new javax.swing.JPanel();
        Option2 = new javax.swing.JLabel();
        Option3Panel = new javax.swing.JPanel();
        Option3 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 700));

        LeftPanel.setBackground(new java.awt.Color(102, 37, 73));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lab 8");

        Option1Panel.setBackground(new java.awt.Color(102, 37, 73));
        Option1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Option1PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Option1PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Option1PanelMouseExited(evt);
            }
        });

        Option1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Option1.setForeground(new java.awt.Color(255, 255, 255));
        Option1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inbox-20_1.png"))); // NOI18N
        Option1.setText("  Inbox");

        javax.swing.GroupLayout Option1PanelLayout = new javax.swing.GroupLayout(Option1Panel);
        Option1Panel.setLayout(Option1PanelLayout);
        Option1PanelLayout.setHorizontalGroup(
            Option1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option1PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Option1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Option1PanelLayout.setVerticalGroup(
            Option1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Option1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Option1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Option2Panel.setBackground(new java.awt.Color(102, 37, 73));
        Option2Panel.setPreferredSize(new java.awt.Dimension(197, 24));
        Option2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Option2PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Option2PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Option2PanelMouseExited(evt);
            }
        });

        Option2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Option2.setForeground(new java.awt.Color(255, 255, 255));
        Option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-outbox-20.png"))); // NOI18N
        Option2.setText("  Outbox");

        javax.swing.GroupLayout Option2PanelLayout = new javax.swing.GroupLayout(Option2Panel);
        Option2Panel.setLayout(Option2PanelLayout);
        Option2PanelLayout.setHorizontalGroup(
            Option2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option2PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Option2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Option2PanelLayout.setVerticalGroup(
            Option2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Option2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        Option3Panel.setBackground(new java.awt.Color(102, 37, 73));
        Option3Panel.setPreferredSize(new java.awt.Dimension(197, 24));
        Option3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Option3PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Option3PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Option3PanelMouseExited(evt);
            }
        });

        Option3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Option3.setForeground(new java.awt.Color(255, 255, 255));
        Option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-compose-20.png"))); // NOI18N
        Option3.setText("  Compose");

        javax.swing.GroupLayout Option3PanelLayout = new javax.swing.GroupLayout(Option3Panel);
        Option3Panel.setLayout(Option3PanelLayout);
        Option3PanelLayout.setHorizontalGroup(
            Option3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option3PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Option3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Option3PanelLayout.setVerticalGroup(
            Option3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option3PanelLayout.createSequentialGroup()
                .addComponent(Option3)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Option1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(Option2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(Option3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(Option1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Option2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Option3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setLayout(new javax.swing.BoxLayout(RightPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void Option1PanelMouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Option1Panel.setBackground(new Color(85, 65, 118));
    }                                         

    private void Option1PanelMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Option1Panel.setBackground(new Color(102, 37, 73));
    }                                        

    private void Option2PanelMouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Option2Panel.setBackground(new Color(85, 65, 118));
        
    }                                         

    private void Option2PanelMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Option2Panel.setBackground(new Color(102, 37, 73));
    }                                        

    private void Option3PanelMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Option3Panel.setBackground(new Color(102, 37, 73));
    }                                        

    private void Option3PanelMouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Option3Panel.setBackground(new Color(85, 65, 118));  
    }                                         

    private void Option1PanelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        JLabel[] array = new JLabel[5];
        for (int i = 0; i < 5; i++){
            array[i] = new JLabel("I am a Label");
            RightPanel.add(array[i]);
        }
        RightPanel.add(new JButton("read"));
        RightPanel.revalidate();
        RightPanel.repaint();
    }                                         

    private void Option2PanelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Option3PanelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Db().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel Option1;
    private javax.swing.JPanel Option1Panel;
    private javax.swing.JLabel Option2;
    private javax.swing.JPanel Option2Panel;
    private javax.swing.JLabel Option3;
    private javax.swing.JPanel Option3Panel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
